### ISSUE TITLE
Brochure

### ISSUE THREAD

**Issue by adina** [adina/communications#11]
something like http://ladieslearningcode.com/AfterschoolBrochure.pdf

**Comment by wking** [comment]
There was some older stuff along these lines in swcarpentry/assets.  That repository is gone now, but I still have my copy.  See [this directory](https://github.com/wking/swc-assets/tree/master/advertising/5.1).

**Comment by wking** [comment]
There's also swcarpentry/communications#8.  What's the distinction between that flyer and the brochure desired here?  Just the medium (single sheet flyer, vs. folded, possibly multi-page brochure)?

**Comment by adina** [comment]
@wking That's what I'm thinking - the brochure is the folded up multipager and the flyer is something you might give to workshop organizers to post on their wall.  Both can be emailed to parties of interest.  I think there is a lot of synergy in designing the two.

**Comment by adina** [comment]
Assigning (unless objection) to @LJWilliams?

**Comment by adina** [comment]
Moved to https://github.com/swcarpentry/communications/issues/20

**Comment by LJWilliams** [comment]
Who is the audience?
