### ISSUE TITLE
New Testimonials

### ISSUE THREAD

**Issue by adina** [adina/communications#12]
http://software-carpentry.org/pages/testimonials.html desperately needs some fresh stories...

**Comment by wking** [comment]
On Sun, Mar 08, 2015 at 07:44:42AM -0700, adina wrote:

> http://software-carpentry.org/pages/testimonials.html desperately
> needs some fresh stories...

I'd suggest keeping all of our collected testimonials in a list or
database somewhere and randomly iterating through them for the live
page.

**Comment by adina** [comment]
https://github.com/swcarpentry/communications/issues
