### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by adina** [adina/communications#5]
We need at least 2 more people on this subcommittee to do after @gvwilson blogpost release

**Comment by LJWilliams** [comment]
I can help if you still need somebody.

Lynne

**Comment by adina** [comment]
You bet!  Is there a specific issue you are interested in?

Thanks!
Adina

**Comment by LJWilliams** [comment]
Nope. Just let me know what is highest priority.

Lynne

**Comment by adina** [comment]
I think this one is high priority:

https://github.com/adina/communications/issues/7

as well as

https://github.com/adina/communications/issues/10

since it came as a request from potential sponsors

Let me know what you think.

**Comment by adina** [comment]
Whoops - sorry to inundate you, I just realized Issue #7 is being address
by Ivan.

How about https://github.com/adina/communications/issues/11?

Thanks so much Lynne -- happy to get some help with these issues.

Adina

**Comment by adina** [comment]
@adina add Amy Brown and update committee membership on blogpost.

**Comment by swaldman3** [comment]
I think I can safely offer to help here! (I've been looking for a way to contribute to SWC without being at instructor level in technical ability).
I like to think that I can write coherent English, and that my design and layout skills are above average amongst scientists... Will take a look at the issues list in the next couple of days.

**Comment by swaldman3** [comment]
Um, I notice that we're using an issue tracker on adina's personal fork of the communications repo, rather than on the main SWC version. Is this correct, and intentional? Is it the best way to do things?

**Comment by adina** [comment]
Hi Simon,

First, thanks for volunteering.  Second, I had been using the one on my
repo (not knowing that I couldn't merge them).  I'll spend some time
transferring them over at some point this week.

Thanks again!
Adina

**Comment by adina** [comment]
All new comments to https://github.com/swcarpentry/communications/issues

**Comment by adina** [comment]
Moved to https://github.com/swcarpentry/communications/issues
